// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package paymentgateway;

@net.sf.jni4net.attributes.ClrType
public class ErrorCodes extends system.Enum {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected ErrorCodes(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    protected ErrorCodes() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
    }
    
    public static system.Type typeof() {
        return paymentgateway.ErrorCodes.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        paymentgateway.ErrorCodes.staticType = staticType;
    }
    //</generated-proxy>
}
