// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package paymentgateway;

@net.sf.jni4net.attributes.ClrType
public class Pay extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected Pay(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public Pay() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        paymentgateway.Pay.__ctorPay0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorPay0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void ready();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean Initialize();
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void close();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LSystem/String;)LPaymentGateway/Receipt;")
    public native paymentgateway.Receipt Purchase(java.lang.String orderId, java.lang.String amount);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LSystem/String;LSystem/String;)LPaymentGateway/Receipt;")
    public native paymentgateway.Receipt Refund(java.lang.String orderId, java.lang.String transId, java.lang.String amount);
    
    @net.sf.jni4net.attributes.ClrMethod("()[LPaymentGateway/BatchRecord;")
    public native paymentgateway.BatchRecord[] CloseBatch();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)LSystem/String;")
    public native java.lang.String process(double amount);
    
    public static system.Type typeof() {
        return paymentgateway.Pay.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        paymentgateway.Pay.staticType = staticType;
    }
    //</generated-proxy>
}
