// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package paymentgateway;

@net.sf.jni4net.attributes.ClrType
public class Receipt extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected Receipt(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public Receipt() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        paymentgateway.Receipt.__ctorReceipt0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorReceipt0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getErrorMessage();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setErrorMessage(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getTipAmount();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setTipAmount(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getTrack2();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getEmvCompletionData();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setEmvCompletionData(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getMCEmvData1();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setMCEmvData1(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getMCEmvData2();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setMCEmvData2(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getMCEmvData3();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setMCEmvData3(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getAppPreferredName();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setAppPreferredName(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getAppLabel();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setAppLabel(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getCardPlan();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setCardPlan(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getAid();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setAid(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getPanEntry();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setPanEntry(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getARQC();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setARQC(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getTvrARQC();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setTvrARQC(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getTCACC();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setTCACC(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getTvrTCACC();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setTvrTCACC(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getCvmIndicator();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setCvmIndicator(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getServiceCode();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setServiceCode(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getTSI();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setTSI(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getCashBackAmount();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setCashBackAmount(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getDebitSurchargeAmount();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setDebitSurchargeAmount(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getCreditSurchargeAmount();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setCreditSurchargeAmount(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getSafCount();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setSafCount(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getEchoData();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setEchoData(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getAvsResult();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setAvsResult(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getCvdResult();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setCvdResult(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getLevel2TaxAmount();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setLevel2TaxAmount(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getResponseCode();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setResponseCode(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getAmount();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setAmount(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getApiToken();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setApiToken(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getTerminalId();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setTerminalId(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getTransType();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setTransType(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LPaymentGateway/TransCode;")
    public native paymentgateway.TransCode getTransCode();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getReceiptId();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setReceiptId(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getRefNum();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setRefNum(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getLevel2Invoice();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setLevel2Invoice(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getCardType();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setCardType(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getAuthCode();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setAuthCode(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getCompleted();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setCompleted(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getIsoCode();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setIsoCode(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getTransTime();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setTransTime(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getMessage();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setMessage(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getOrderId();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setOrderId(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getStoreId();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setStoreId(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getTransactionNo();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setTransactionNo(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getSignature();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setSignature(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getEcom();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setEcom(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getAccountType();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setAccountType(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getLang();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setLang(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getTransDate();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setTransDate(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getPan();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setPan(java.lang.String value);
    
    public static system.Type typeof() {
        return paymentgateway.Receipt.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        paymentgateway.Receipt.staticType = staticType;
    }
    //</generated-proxy>
}
