//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentGateway {
    
    
    #region Component Designer generated code 
    public partial class Pay_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::PaymentGateway.@__Pay.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::PaymentGateway.Pay), typeof(global::PaymentGateway.Pay_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::PaymentGateway.Pay), typeof(global::PaymentGateway.Pay_))]
    internal sealed partial class @__Pay : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__Pay(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::PaymentGateway.@__Pay.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__Pay);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ready", "ready0", "()V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Initialize", "Initialize1", "()Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "close", "close2", "()V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Purchase", "Purchase3", "(Ljava/lang/String;Ljava/lang/String;)Lpaymentgateway/Receipt;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Purchase", "Purchase4", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lpaymen" +
                        "tgateway/Receipt;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Refund", "Refund5", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lpaymentgateway/Receipt;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Refund", "Refund6", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/la" +
                        "ng/String;)Lpaymentgateway/Receipt;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "CloseBatch", "CloseBatch7", "()[Lpaymentgateway/BatchRecord;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "process", "process8", "(D)Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorPay0", "__ctorPay0", "(Lnet/sf/jni4net/inj/IClrProxy;)V"));
            return methods;
        }
        
        private static void ready0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::PaymentGateway.Pay @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::PaymentGateway.Pay>(@__env, @__obj);
            @__real.ready();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static bool Initialize1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Z
            // ()Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::PaymentGateway.Pay @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::PaymentGateway.Pay>(@__env, @__obj);
            @__return = ((bool)(@__real.Initialize()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void close2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::PaymentGateway.Pay @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::PaymentGateway.Pay>(@__env, @__obj);
            @__real.close();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Purchase3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle orderId, global::net.sf.jni4net.utils.JniLocalHandle amount) {
            // (Ljava/lang/String;Ljava/lang/String;)Lpaymentgateway/Receipt;
            // (LSystem/String;LSystem/String;)LPaymentGateway/Receipt;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::PaymentGateway.Pay @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::PaymentGateway.Pay>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::PaymentGateway.Receipt>(@__env, @__real.Purchase(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, orderId), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, amount)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Purchase4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle orderId, global::net.sf.jni4net.utils.JniLocalHandle amount, global::net.sf.jni4net.utils.JniLocalHandle ccNum, global::net.sf.jni4net.utils.JniLocalHandle expiry) {
            // (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lpaymentgateway/Receipt;
            // (LSystem/String;LSystem/String;LSystem/String;LSystem/String;)LPaymentGateway/Receipt;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::PaymentGateway.Pay @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::PaymentGateway.Pay>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::PaymentGateway.Receipt>(@__env, @__real.Purchase(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, orderId), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, amount), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, ccNum), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, expiry)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Refund5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle orderId, global::net.sf.jni4net.utils.JniLocalHandle transId, global::net.sf.jni4net.utils.JniLocalHandle amount) {
            // (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lpaymentgateway/Receipt;
            // (LSystem/String;LSystem/String;LSystem/String;)LPaymentGateway/Receipt;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::PaymentGateway.Pay @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::PaymentGateway.Pay>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::PaymentGateway.Receipt>(@__env, @__real.Refund(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, orderId), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, transId), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, amount)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Refund6(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle orderId, global::net.sf.jni4net.utils.JniLocalHandle transId, global::net.sf.jni4net.utils.JniLocalHandle amount, global::net.sf.jni4net.utils.JniLocalHandle ccNum, global::net.sf.jni4net.utils.JniLocalHandle expiry) {
            // (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lpaymentgateway/Receipt;
            // (LSystem/String;LSystem/String;LSystem/String;LSystem/String;LSystem/String;)LPaymentGateway/Receipt;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::PaymentGateway.Pay @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::PaymentGateway.Pay>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::PaymentGateway.Receipt>(@__env, @__real.Refund(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, orderId), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, transId), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, amount), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, ccNum), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, expiry)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle CloseBatch7(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()[Lpaymentgateway/BatchRecord;
            // ()[LPaymentGateway/BatchRecord;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::PaymentGateway.Pay @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::PaymentGateway.Pay>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayStrongC2Jp<global::PaymentGateway.BatchRecord[], global::PaymentGateway.BatchRecord>(@__env, @__real.CloseBatch());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle process8(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double amount) {
            // (D)Ljava/lang/String;
            // (D)LSystem/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::PaymentGateway.Pay @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::PaymentGateway.Pay>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2JString(@__env, @__real.process(amount));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void @__ctorPay0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::PaymentGateway.Pay @__real = new global::PaymentGateway.Pay();
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::PaymentGateway.@__Pay(@__env);
            }
        }
    }
    #endregion
}
